# EDA

This notebook will be used for exploratory data analysis for the hotel booking cancellation risk prediction project.

Import dependencies:

In [30]:
import sqlite3
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as pp

Check tables in hotel database records:

In [31]:
conn = sqlite3.connect('hotel.db')
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print("Tables in db", cursor.fetchall())

Tables in db [('bookings',), ('reviews',)]

Preview bookings table's data structure and summary:

In [32]:
df_bookings = pd.read_sql_query("SELECT * FROM bookings", conn)
df_bookings.head()

,Unnamed: 0,booking_id,client_email,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,promo_code
0,112427,SG134998,jia.ng9250@outlook.com,Airport Hotel,0,94,2025,May,20,16,...,240.0,,0,Transient,230,0,1,Check-Out,2025-05-19 00:00:00,EARLYBIRD
1,95089,SG109835,david.kumar3843@hotmail.com,Airport Hotel,1,103,2025,March,13,27,...,495.0,Kallang Industries,0,Transient,167.9,0,0,Canceled,2024-12-23 00:00:00,
2,78527,SG207272,mei.low3636@icloud.com,City Hotel,0,83,2025,Apr,17,23,...,9.0,,0,Transient,27.6,0,2,Check-Out,2025-04-28 00:00:00,STAY3PAY2
3,76840,SG115106,arjun.ong1474@yahoo.com.sg,Airport Hotel,0,48,2023,August,35,27,...,196.0,,0,Transient,246.1,1,0,Check-Out,2023-08-31 00:00:00,FLASH
4,1167,SG182301,arjun.kumar398@icloud.com,City Hotel,0,1,2024,March,11,9,...,9.0,,0,Transient-Party,218.5,0,0,Check-Out,2024-03-10 00:00:00,

In [33]:
df_bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 118549 entries, 0 to 118548
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unnamed: 0                      118549 non-null  str
 1   booking_id                      118549 non-null  str
 2   client_email                    118549 non-null  str
 3   hotel                           118549 non-null  str
 4   is_canceled                     118549 non-null  str
 5   lead_time                       118549 non-null  str
 6   arrival_date_year               118549 non-null  str
 7   arrival_date_month              118549 non-null  str
 8   arrival_date_week_number        118549 non-null  str
 9   arrival_date_day_of_month       118549 non-null  str
 10  stays_in_weekend_nights         118549 non-null  str
 11  stays_in_week_nights            118549 non-null  str
 12  adults                          118549 non-null  str
 13  children                        118549 non-null  str
 14  babies                          118549 non-null  str
 15  meal                            118549 non-null  str
 16  country                         118549 non-null  str
 17  market_segment                  118549 non-null  str
 18  distribution_channel            118549 non-null  str
 19  is_repeated_guest               118549 non-null  str
 20  previous_cancellations          118549 non-null  str
 21  previous_bookings_not_canceled  118549 non-null  str
 22  reserved_room_type              118549 non-null  str
 23  assigned_room_type              118549 non-null  str
 24  booking_changes                 118549 non-null  str
 25  deposit_type                    118549 non-null  str
 26  agent                           118549 non-null  str
 27  company                         118549 non-null  str
 28  days_in_waiting_list            118549 non-null  str
 29  customer_type                   118549 non-null  str
 30  adr                             118549 non-null  str
 31  required_car_parking_spaces     118549 non-null  str
 32  total_of_special_requests       118549 non-null  str
 33  reservation_status              118549 non-null  str
 34  reservation_status_date         118549 non-null  str
 35  promo_code                      118549 non-null  str
dtypes: str(36)
memory usage: 32.6 MB

Preview reviews table's data structure and summary:

In [34]:
df_reviews = pd.read_sql_query("SELECT * FROM reviews", conn)
df_reviews.head()

,client_email,rating,comments
0,farah.wong8097@gmail.com,4,"A hassle-free stay. The room was bright, nothi..."
1,grace.goh4995@hotmail.com,5,A world-class stay — the staff went above and ...
2,arjun.iskandar6575@icloud.com,5,Couldn't have asked for more — the team could ...
3,daniel.raj4258@outlook.com,4,"A fuss-free stay. Check-in was smooth, a relia..."
4,zhen.koh776@icloud.com,5,An unforgettable stay. The team could not do e...

In [35]:
df_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 17583 entries, 0 to 17582
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_email  17583 non-null  str
 1   rating        17583 non-null  str
 2   comments      17583 non-null  str
dtypes: str(3)
memory usage: 412.2 KB

Detect missing values:

In [36]:
df_bookings.isnull().sum()

Unnamed: 0                        0
booking_id                        0
client_email                      0
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
promo_code                        0
dtype: int64

In [37]:
df_reviews.isnull().sum()

client_email    0
rating          0
comments        0
dtype: int64

Check descriptive statistics:

In [ ]:
df_bookings.describe().T

In [44]:
df_reviews.describe().T

              count unique                        top   freq
client_email  17583  17532  ravi.see7277@yahoo.com.sg      2
rating        17583      7                          4  10635
comments      17583  16839                               332

Identify duplicates:

In [45]:
df_bookings.duplicated().sum()

np.int64(353)

In [46]:
df_reviews.duplicated().sum()

np.int64(51)

In [47]:
df_bookings[df_bookings.duplicated(keep=False)].sort_values(by=list(df_bookings.columns))

,Unnamed: 0,booking_id,client_email,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,promo_code
24779,100393,SG191801,daniel.koh4626@gmail.com,City Hotel,0,102,2024,August,32,6,...,85.0,Pacific Enterprises,0,Transient,146.62,0,0,Check-Out,2024-08-08 00:00:00,SAVE10
58673,100393,SG191801,daniel.koh4626@gmail.com,City Hotel,0,102,2024,August,32,6,...,85.0,Pacific Enterprises,0,Transient,146.62,0,0,Check-Out,2024-08-08 00:00:00,SAVE10
74476,100573,SG174796,ravi.wong9928@yahoo.com.sg,City Hotel,0,2,2023,September,39,21,...,,,0,Transient,259.9,0,0,Check-Out,2023-09-24 00:00:00,EARLYBIRD
86671,100573,SG174796,ravi.wong9928@yahoo.com.sg,City Hotel,0,2,2023,September,39,21,...,,,0,Transient,259.9,0,0,Check-Out,2023-09-24 00:00:00,EARLYBIRD
34719,101018,SG203416,sarah.lim6727@hotmail.com,City Hotel,0,47,2025,February,7,18,...,7.0,Straits Logistics,0,Transient,205.94,0,1,Check-Out,2025-02-24 00:00:00,CORP15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100146,99654,SG179036,wei.kumar4317@yahoo.com.sg,City Hotel,1,178,2024,April,18,28,...,19.0,,46,Transient,253,0,0,Canceled,2023-12-18 00:00:00,
1763,99720,SG168078,sarah.sim4211@outlook.com,City Hotel,1,169,2025,June,23,8,...,19.0,,0,Transient,391,0,0,Canceled,2024-12-21 00:00:00,
23929,99720,SG168078,sarah.sim4211@outlook.com,City Hotel,1,169,2025,June,23,8,...,19.0,,0,Transient,391,0,0,Canceled,2024-12-21 00:00:00,
33665,99926,SG116220,hakim.rahman5629@hotmail.com,Airport Hotel,0,7,2023,October,42,12,...,240.0,Straits Trading,0,Transient,138.92,0,2,Check-Out,2023-10-17 00:00:00,
44317,99926,SG116220,hakim.rahman5629@hotmail.com,Airport Hotel,0,7,2023,October,42,12,...,240.0,Straits Trading,0,Transient,138.92,0,2,Check-Out,2023-10-17 00:00:00,