# EDA

This notebook will be used for exploratory data analysis for the hotel booking cancellation risk prediction project.

### Section 1: Import dependencies:

In [30]:
import sqlite3
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as pp

### Section 2: Analyze data in hotel records

##### 2.1. Analyze bookings table

In [ ]:
## connect to db
conn = sqlite3.connect('hotel.db')
cursor = conn.cursor()

## check tables in db
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print("Tables in db", cursor.fetchall())

Tables in db [('bookings',), ('reviews',)]

In [ ]:
# preview table data structure
df_bookings = pd.read_sql_query("SELECT * FROM bookings", conn)
df_bookings.head()

In [ ]:
# preview table summary info => all non-null values, skip missing values check
df_bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 118549 entries, 0 to 118548
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unnamed: 0                      118549 non-null  str
 1   booking_id                      118549 non-null  str
 2   client_email                    118549 non-null  str
 3   hotel                           118549 non-null  str
 4   is_canceled                     118549 non-null  str
 5   lead_time                       118549 non-null  str
 6   arrival_date_year               118549 non-null  str
 7   arrival_date_month              118549 non-null  str
 8   arrival_date_week_number        118549 non-null  str
 9   arrival_date_day_of_month       118549 non-null  str
 10  stays_in_weekend_nights         118549 non-null  str
 11  stays_in_week_nights            118549 non-null  str
 12  adults                          118549 non-null  str
 13  children                        118549 non-null  str
 14  babies                          118549 non-null  str
 15  meal                            118549 non-null  str
 16  country                         118549 non-null  str
 17  market_segment                  118549 non-null  str
 18  distribution_channel            118549 non-null  str
 19  is_repeated_guest               118549 non-null  str
 20  previous_cancellations          118549 non-null  str
 21  previous_bookings_not_canceled  118549 non-null  str
 22  reserved_room_type              118549 non-null  str
 23  assigned_room_type              118549 non-null  str
 24  booking_changes                 118549 non-null  str
 25  deposit_type                    118549 non-null  str
 26  agent                           118549 non-null  str
 27  company                         118549 non-null  str
 28  days_in_waiting_list            118549 non-null  str
 29  customer_type                   118549 non-null  str
 30  adr                             118549 non-null  str
 31  required_car_parking_spaces     118549 non-null  str
 32  total_of_special_requests       118549 non-null  str
 33  reservation_status              118549 non-null  str
 34  reservation_status_date         118549 non-null  str
 35  promo_code                      118549 non-null  str
dtypes: str(36)
memory usage: 32.6 MB

In [ ]:
# check descriptive statistics
df_bookings.describe().T

In [ ]:
# check duplicate record count => 353 duplicate records
df_bookings.duplicated().sum()

np.int64(353)

In [ ]:
# sort and display duplicated records
df_bookings[df_bookings.duplicated(keep=False)].sort_values(by=list(df_bookings.columns))

In [64]:
# check consistency of is_canceled column => inconsistent values found, should be 0 or 1
df_bookings['is_canceled'].unique()

<StringArray>
['0', '1', 'true', 'false', 'No', 'Yes']
Length: 6, dtype: str

##### 2.2. Analyze reviews table

In [ ]:
# preview table's data structure
df_reviews = pd.read_sql_query("SELECT * FROM reviews", conn)
df_reviews.head()

In [ ]:
# preview table summary info => all non-null values, skip missing values check
df_reviews.info()

<class 'pandas.DataFrame'>
Index: 17532 entries, 0 to 17582
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_email  17532 non-null  str
 1   rating        17532 non-null  str
 2   comments      17532 non-null  str
dtypes: str(3)
memory usage: 547.9 KB

In [ ]:
# check descriptive statistics
df_reviews.describe().T

              count unique                        top   freq
client_email  17583  17532  ravi.see7277@yahoo.com.sg      2
rating        17583      7                          4  10635
comments      17583  16839                               332

In [ ]:
# check duplicate record count => 51 duplicate records
df_reviews.duplicated().sum()

np.int64(51)

In [51]:
df_reviews[df_reviews.duplicated(keep=False)].sort_values(by=list(df_reviews.columns))

,client_email,rating,comments
609,aaron.nair2119@outlook.com,4,"A pleasant stay. The front desk was helpful, w..."
11762,aaron.nair2119@outlook.com,4,"A pleasant stay. The front desk was helpful, w..."
11936,chloe.iskandar5543@hotmail.com,4,"A satisfying stay; the facilities were good, a..."
17004,chloe.iskandar5543@hotmail.com,4,"A satisfying stay; the facilities were good, a..."
8399,daniel.low4910@yahoo.com.sg,5,The staff went above and beyond; an outstandin...
...,...,...,...
13877,yuki.tan2414@hotmail.com,5,The whole team was wonderful; an outstanding s...
4148,zhen.nair3603@gmail.com,4,"Service was attentive; a smooth stay, not perf..."
17101,zhen.nair3603@gmail.com,4,"Service was attentive; a smooth stay, not perf..."
8917,zhen.ng9239@hotmail.com,4,"Check-in was smooth; a tidy, comfortable stay,..."
17542,zhen.ng9239@hotmail.com,4,"Check-in was smooth; a tidy, comfortable stay,..."

#### Section 3: Data cleaning and processing

In [ ]:
# remove duplicate records from both tables
df_bookings.drop_duplicates(inplace=True)
df_reviews.drop_duplicates(inplace=True)

<StringArray>
['0', '1', 'true', 'false', 'No', 'Yes']
Length: 6, dtype: str